# Generated by Django 3.2.5 on 2024-04-02 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(blank=True, max_length=10, null=True)),
                ('anio', models.CharField(max_length=5)),
                ('mes', models.CharField(max_length=3)),
                ('cod_prov', models.CharField(blank=True, max_length=10, null=True)),
                ('cod_microred', models.CharField(blank=True, max_length=10, null=True)),
                ('cod_dist', models.CharField(blank=True, max_length=10, null=True)),
                ('sector', models.CharField(blank=True, max_length=50, null=True)),
                ('provincia', models.CharField(blank=True, max_length=150, null=True)),
                ('distrito', models.CharField(blank=True, max_length=150, null=True)),
                ('eess', models.CharField(blank=True, max_length=250, null=True)),
                ('bcg', models.IntegerField()),
                ('hvb', models.IntegerField()),
                ('apo3', models.IntegerField()),
                ('penta3', models.IntegerField()),
                ('rota2', models.IntegerField()),
                ('neumo2', models.IntegerField()),
                ('spr1', models.IntegerField()),
                ('neumo3', models.IntegerField()),
                ('varicela1', models.IntegerField()),
                ('ama', models.IntegerField()),
                ('spr2', models.IntegerField()),
                ('dpt1_ref', models.IntegerField()),
                ('apo1_ref', models.IntegerField()),
                ('infl2_kids', models.IntegerField()),
                ('infl3_kids', models.IntegerField()),
                ('dpt2_ref', models.IntegerField()),
                ('apo2_ref', models.IntegerField()),
                ('infl4_kids', models.IntegerField()),
                ('vph_girl', models.IntegerField()),
                ('vph_boy', models.IntegerField()),
                ('tdap_preg', models.IntegerField()),
                ('infl_adult', models.IntegerField()),
                ('neumo_adult', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='metaCoverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.CharField(blank=True, max_length=5, null=True)),
                ('cod_prov', models.CharField(blank=True, max_length=10, null=True)),
                ('cod_microred', models.CharField(blank=True, max_length=10, null=True)),
                ('cod_dist', models.CharField(blank=True, max_length=10, null=True)),
                ('provincia', models.CharField(blank=True, max_length=150, null=True)),
                ('distrito', models.CharField(blank=True, max_length=150, null=True)),
                ('less_1year', models.IntegerField()),
                ('one_year', models.IntegerField()),
                ('two_year', models.IntegerField()),
                ('three_year', models.IntegerField()),
                ('four_year', models.IntegerField()),
                ('pregnant', models.IntegerField()),
                ('adult60', models.IntegerField()),
                ('adult30', models.IntegerField()),
                ('girl9_13', models.IntegerField()),
                ('boy9_13', models.IntegerField()),
            ],
        ),
    ]
