# Generated by Django 3.2.5 on 2024-03-07 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('redes', '0003_auto_20240229_1220'),
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_red',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='redes.redes'),
        ),
    ]
