# Generated by Django 3.2.5 on 2024-03-10 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('redes', '0003_auto_20240229_1220'),
        ('person', '0002_user_id_red'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='eid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='redes.entity'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='date_update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
