# Generated by Django 3.2.5 on 2024-03-12 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(blank=True, max_length=10, null=True)),
                ('anio', models.CharField(blank=True, max_length=5, null=True)),
                ('mes', models.CharField(blank=True, max_length=3, null=True)),
                ('provincia', models.CharField(blank=True, max_length=150, null=True)),
                ('distrito', models.CharField(blank=True, max_length=150, null=True)),
                ('establecimiento', models.CharField(blank=True, max_length=250, null=True)),
                ('documento', models.CharField(blank=True, max_length=15, null=True)),
                ('fec_1erAte', models.DateField(blank=True, null=True)),
                ('fec_hb', models.DateField(blank=True, null=True)),
                ('den', models.CharField(blank=True, max_length=15, null=True)),
                ('num', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
    ]
