# Generated by Django 3.2.5 on 2024-03-21 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fed2324', '0002_packchild'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packchild',
            name='ape_nombres',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='packchild',
            name='seguro',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
