# Generated by Django 3.2.5 on 2024-02-26 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('eid', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('user_create', models.CharField(blank=True, max_length=50, null=True)),
                ('user_update', models.CharField(blank=True, max_length=50, null=True)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Redes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=15, null=True)),
                ('name', models.CharField(max_length=200)),
                ('abbreviation', models.CharField(blank=True, max_length=10, null=True)),
                ('parent', models.CharField(blank=True, max_length=15, null=True)),
                ('state', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], max_length=2)),
                ('level', models.CharField(choices=[('1', 'Region'), ('2', 'Provincia'), ('3', 'Distrito')], max_length=1)),
                ('user_create', models.CharField(blank=True, max_length=50, null=True)),
                ('user_update', models.CharField(blank=True, max_length=50, null=True)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True, null=True)),
                ('eid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='redes.entity')),
            ],
        ),
    ]
