# Generated by Django 3.2.5 on 2024-02-29 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redes', '0002_auto_20240227_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='user_create',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='user_update',
        ),
        migrations.RemoveField(
            model_name='redes',
            name='user_create',
        ),
        migrations.RemoveField(
            model_name='redes',
            name='user_update',
        ),
        migrations.AddField(
            model_name='entity',
            name='region',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='redes',
            name='type',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='redes',
            name='code',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='redes',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='redes',
            name='level',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
